# Generated by Django 6.0.4 on 2026-05-19 14:03

from django.db import migrations, models


def rename_minimal_to_professional(apps, _schema_editor):
    CVBuilderJob = apps.get_model('converter', 'CVBuilderJob')
    CVBuilderJob.objects.filter(template='minimal').update(template='professional')


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rename_minimal_to_professional, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cvbuilderjob',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic'), ('professional', 'Professional'), ('modern', 'Modern'), ('creative', 'Creative'), ('developer', 'Developer')], default='classic', max_length=20),
        ),
    ]
