# Generated by Django 6.0.4 on 2026-05-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_rename_minimal_to_professional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvbuilderjob',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic'), ('professional', 'Professional'), ('lebenslauf', 'Lebenslauf'), ('modern', 'Modern'), ('creative', 'Creative'), ('developer', 'Developer')], default='classic', max_length=20),
        ),
    ]
