# Generated by Django 6.0.4 on 2026-05-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_add_lebenslauf_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvbuilderjob',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic'), ('professional', 'Professional'), ('lebenslauf', 'Lebenslauf'), ('german2', 'German Modern'), ('magnific', 'Magnific'), ('modern', 'Modern'), ('creative', 'Creative'), ('developer', 'Developer')], default='classic', max_length=20),
        ),
    ]
