# Generated by Django 6.0.4 on 2026-05-06 16:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cv_limit', models.IntegerField(help_text='-1 = unlimited')),
                ('is_monthly', models.BooleanField(default=False, help_text='If True, limit resets monthly')),
                ('features', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('user', 'User')], default='user', max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('google_id', models.CharField(blank=True, max_length=128)),
                ('facebook_id', models.CharField(blank=True, max_length=128)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Amount in cents')),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('plan', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund')], default='payment', max_length=20)),
                ('status', models.CharField(default='paid', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_count', models.IntegerField(default=0)),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunSQL(
            sql="""
                INSERT INTO accounts_plan (name, display_name, price, cv_limit, is_monthly, features)
                VALUES
                    ('free',    'Free',    0.00,  1,  false, '["Shareable portfolio link", "1 CV generation (lifetime)", "AI-powered unique design", "Tailwind CSS portfolio", "HTML download"]'),
                    ('starter', 'Starter', 19.00, 15, true,  '["Shareable portfolio link", "15 CV generations per month", "AI-powered unique designs", "All design styles & animations", "HTML download", "Priority processing", "GitHub Pages deployment (coming soon)", "cPanel deployment (coming soon)"]'),
                    ('pro',     'Pro',     49.00, 40, true,  '["Shareable portfolio link", "40 CV generations per month", "AI-powered unique designs", "All design styles & animations", "HTML download", "Priority processing", "GitHub Pages auto-deploy (coming soon)", "AWS S3 auto-deploy (coming soon)", "cPanel auto-deploy (coming soon)", "Early access to new features"]')
                ON CONFLICT (name) DO UPDATE SET
                    display_name = EXCLUDED.display_name,
                    price        = EXCLUDED.price,
                    cv_limit     = EXCLUDED.cv_limit,
                    is_monthly   = EXCLUDED.is_monthly,
                    features     = EXCLUDED.features;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
